apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: pingservice
  name: pingservice
  selfLink: /oapi/v1/namespaces/pingservice-dev/buildconfigs/pingservice
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: pingservice:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-openliberty:19.0.0.8-jdk1.8
        namespace: ci-cd
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 3z1v5qc5g8Ea889l46sS
    type: GitHub
  - generic:
      secret: N8T2_Ga0Tl-89fpN26K5
    type: Generic
status:
  lastVersion: 1
