apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewBuild"},"creationTimestamp":null,"labels":{"build":"pingservice"},"name":"pingservice","namespace":"pingservice-development","selfLink":"/oapi/v1/namespaces/pingservice-development/buildconfigs/pingservice"},"spec":{"failedBuildsHistoryLimit":5,"nodeSelector":null,"output":{"to":{"kind":"ImageStreamTag","name":"pingservice:latest"}},"postCommit":{},"resources":{},"runPolicy":"Serial","source":{"binary":{},"type":"Binary"},"strategy":{"sourceStrategy":{"from":{"kind":"ImageStreamTag","name":"s2i-openliberty:19.0.0.8-jdk11","namespace":"ci-cd"}},"type":"Source"},"successfulBuildsHistoryLimit":5,"triggers":[{"github":{"secret":"1CAs8gW_70KVgl7-zZut"},"type":"GitHub"},{"generic":{"secret":"aHtpSFCW6lxCBwsv6-a3"},"type":"Generic"}]},"status":{"lastVersion":4}}
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: pingservice
  name: pingservice
  selfLink: /oapi/v1/namespaces/pingservice-development/buildconfigs/pingservice
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: pingservice:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-openliberty:19.0.0.8-jdk11
        namespace: ci-cd
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 1CAs8gW_70KVgl7-zZut
    type: GitHub
  - generic:
      secret: aHtpSFCW6lxCBwsv6-a3
    type: Generic
status:
  lastVersion: 5
