apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: pingservice
  name: pingservice
  selfLink: /oapi/v1/namespaces/pingservice-development/buildconfigs/pingservice
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: pingservice:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-openliberty:19.0.0.8-jdk11
        namespace: ci-cd
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 7gjMgQQTZY4uXcs_s7G_
    type: GitHub
  - generic:
      secret: gQkOiEIB-PLtcF9V3jc9
    type: Generic
status:
  lastVersion: 0
