apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: pingservice
  name: pingservice
  selfLink: /api/v1/namespaces/pingservice-dev/services/pingservice
spec:
  ports:
  - name: 9080-tcp
    port: 9080
    protocol: TCP
    targetPort: 9080
  - name: 9443-tcp
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app: pingservice
    deploymentconfig: pingservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
