apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: PingService
    env: PROD
  name: pingservice-pipeline-prod
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources:
    requests:
      cpu: 500Mi
      memory: 500M
  runPolicy: SerialLatestOnly
  source:
    git:
      ref: master
      uri: https://github.com/codelair-io/devopspath-build-pingservice.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ci/Jenkinsfile.prod
    type: JenkinsPipeline
